<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '55f196778b819e48453d840a40fa315f' => $vendorDir . '/fffunction/twig-static/src/twig-static.php',
);
