<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdd3a576a6876fc8854b8081497538140
{
    public static $files = array (
        '55f196778b819e48453d840a40fa315f' => __DIR__ . '/..' . '/fffunction/twig-static/src/twig-static.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {

        }, null, ClassLoader::class);
    }
}
